### ISSUE TITLE
Weighted Edges

### ISSUE THREAD

**Issue by icio** [sverweij/state-machine-cat#141]
### Context

I've been processing our API request logs and building state machines of the entities transitions described within them. Here's a very small examples of a few requests from a test account:

![image](https://user-images.githubusercontent.com/408401/119976997-c6c65200-bfaf-11eb-936c-f27f2733be9f.png)

At the bottom of each transition label is the count of entities that followed that path followed by the percentage of total entities in brackets.

I would like to add more visual weight to the more frequently travelled paths.

### Proposed Behavior

Allow the specification of some weight attribute on transitions that can be used to increase the stroke width of a transition's arrow.

### Current Behavior

Adding any such weight would cause an error. Using `active` on the most frequent states would not communicate what I want.

### Considered alternatives

Previously I was only using the label to write how frequently-travelled an edge was, but I've since hacked in weight edges using the `class`. I can give a transition a class `weight-0` to `weight-100` which I choose from the percentage assigned to transition. And then I have a CSS file:

```css
.weight-0 { stroke-width: 1.0px; }
.weight-1 { stroke-width: 1.040px; }
.weight-2 { stroke-width: 1.080px; }
.weight-3 { stroke-width: 1.120px; }
.weight-4 { stroke-width: 1.160px; }
.weight-5 { stroke-width: 1.20px; }
/* ... */
.weight-95 { stroke-width: 4.80px; }
.weight-96 { stroke-width: 4.840px; }
.weight-97 { stroke-width: 4.880px; }
.weight-98 { stroke-width: 4.920px; }
.weight-99 { stroke-width: 4.960px; }
.weight-100 { stroke-width: 5.0px; }
```

which I generated using the following command in bash

```bash
for i in {0..100}; do echo ".weight-$i { stroke-width: $(echo 1 + 4 \* $i / 100 | bc -l)px; }"; done | sed -r 's/0+px/0px/g'
```

The result is the following kind of visualisation. I had to mask the labels and colours of as I didn't have any good test examples:

![image](https://user-images.githubusercontent.com/408401/119978419-87990080-bfb1-11eb-8790-9c7424b083ac.png)

Thanks again for the terrific library!
